# Generated by Django 4.2.11 on 2024-05-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criterias',
            },
        ),
        migrations.CreateModel(
            name='Methodologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название методологии')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Описание варианта ответа')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.criterias')),
            ],
            options={
                'verbose_name': 'Options',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.methodologies')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.options')),
            ],
            options={
                'verbose_name': 'Scores',
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.CreateModel(
            name='CriteriasPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Score')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='model.criterias')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='model.criterias')),
            ],
        ),
    ]
