# Generated by Django 4.2.11 on 2024-05-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriaspriority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.RemoveField(
            model_name='criteriaspriority',
            name='first',
        ),
        migrations.RemoveField(
            model_name='criteriaspriority',
            name='second',
        ),
        migrations.AddField(
            model_name='criteriaspriority',
            name='first_cr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.criterias'),
        ),
        migrations.AddField(
            model_name='criteriaspriority',
            name='second_cr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='model.criterias'),
        ),
        migrations.AlterField(
            model_name='criteriaspriority',
            name='priority',
            field=models.IntegerField(verbose_name='Priority'),
        ),
    ]
