# Generated by Django 4.2.11 on 2024-05-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_criteriaspriority_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteriaspriority',
            old_name='second_cr',
            new_name='criteria',
        ),
        migrations.RemoveField(
            model_name='criteriaspriority',
            name='first_cr',
        ),
    ]
