# Generated by Django 4.2.11 on 2024-05-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_rename_second_cr_criteriaspriority_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaspriority',
            name='_criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='model.criterias'),
        ),
        migrations.AlterField(
            model_name='criteriaspriority',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='model.criterias'),
        ),
    ]
