# Generated by Django 4.2.11 on 2024-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_criteriaspriority__criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaspriority',
            name='priority',
            field=models.FloatField(verbose_name='Priority'),
        ),
    ]
