# Generated by Django 4.2.11 on 2024-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_criterias_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='description',
            field=models.TextField(verbose_name='Описание варианта ответа'),
        ),
    ]
